"""Added size to image model

Revision ID: 68dc362e728f
Revises: 1f65c3143a01
Create Date: 2026-07-20 13:42:32.193182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68dc362e728f'
down_revision: Union[str, Sequence[str], None] = '1f65c3143a01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'image',
        sa.Column('size_bytes', sa.Integer(), nullable=False, server_default='0'),
    )
    op.alter_column('image', 'size_bytes', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image', 'size_bytes')
    # ### end Alembic commands ###
