"""add phase 2 enrichment models

Revision ID: fd5b6be0fe4e
Revises: 68dc362e728f
Create Date: 2026-08-07 14:07:22.193684

"""

from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd5b6be0fe4e"
down_revision: Union[str, Sequence[str], None] = "68dc362e728f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "caption",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column(
            "image_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["image_id"], ["image.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_caption_image_id"), "caption", ["image_id"], unique=False)
    op.create_table(
        "detected_object",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column(
            "image_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column("class_name", sa.String(length=255), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("bounding_box", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["image_id"], ["image.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_detected_object_image_id"),
        "detected_object",
        ["image_id"],
        unique=False,
    )
    op.create_table(
        "ocr_result",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column(
            "image_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False
        ),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("language", sa.String(length=50), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["image_id"], ["image.id"], ondelete="cascade"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ocr_result_image_id"), "ocr_result", ["image_id"], unique=False
    )
    op.add_column("image", sa.Column("dominant_colors", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("image", "dominant_colors")
    op.drop_index(op.f("ix_ocr_result_image_id"), table_name="ocr_result")
    op.drop_table("ocr_result")
    op.drop_index(op.f("ix_detected_object_image_id"), table_name="detected_object")
    op.drop_table("detected_object")
    op.drop_index(op.f("ix_caption_image_id"), table_name="caption")
    op.drop_table("caption")
    # ### end Alembic commands ###
